CREATE TABLE Item (
	ItemID INTEGER NOT NULL,
	Name VARCHAR(100),
	Currently DECIMAL(8,2) NOT NULL,
	Buy_Price DECIMAL(8,2) DEFAULT NULL,
	First_Bid DECIMAL(8,2) NOT NULL,
	Number_of_Bids INTEGER NOT NULL,
	Location VARCHAR(50) NOT NULL,
	Latitude VARCHAR(50) DEFAULT NULL,
	Longitude VARCHAR(50) DEFAULT NULL,
	Country VARCHAR(30) NOT NULL,
	Started TIMESTAMP NOT NULL,
	Ends TIMESTAMP NOT NULL,
	UserID VARCHAR(100) NOT NULL,
	Description VARCHAR(4000) NOT NULL,
	PRIMARY KEY(ItemID)
);

CREATE TABLE Category (
	ItemID INTEGER NOT NULL,
	Category VARCHAR(100) NOT NULL,
	PRIMARY KEY(ItemID, Category)
);

CREATE TABLE Bid (
	ItemID INTEGER NOT NULL,
	UserID VARCHAR(100) NOT NULL,
	Time TIMESTAMP NOT NULL.
	Amount DECIMAL(8,2) NOT NULL,
	PRIMARY KEY(ItemID, UserID, Time)
);

CREATE TABLE User (
	UserID VARCHAR(100) NOT NULL,
	Bidder_Rating INTEGER NOT NULL,
	Seller_Rating INTEGER NOT NULL,
	Location VARCHAR(50),
	Country VARCHAR(30),
	PRIMARY KEY(UserID)
);