LOAD DATA LOCAL INFILE 'item.csv' INTO TABLE User
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'category.csv' INTO TABLE User
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'bid.csv' INTO TABLE User
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';

LOAD DATA LOCAL INFILE 'user.csv' INTO TABLE User
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"';